apiVersion: apps/v1
kind: Deployment
metadata:
  name: datetime-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: datetime-app
  template:
    metadata:
      labels:
        app: datetime-app
    spec:
      containers:
      - name: datetime-app
        image: byaliatharva/date-time-app:latest  # Make sure this is correct
        ports:
        - containerPort: 8080
