apiVersion: v1
kind: Service
metadata:
  name: datetime-app-service
spec:
  type: NodePort
  selector:
    app: datetime-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000  # Choose a port between 30000-32767
